"""changed pose model

Revision ID: 28ebc2748c1d
Revises: 
Create Date: 2024-10-10 18:27:49.111726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ebc2748c1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pose')
    with op.batch_alter_table('Pose_Table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pose_data', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'User_Table', ['user_id'], ['id'])
        batch_op.drop_column('is_correct')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pose_Table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('feedback')
        batch_op.drop_column('pose_data')
        batch_op.drop_column('user_id')

    op.create_table('pose',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pose_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User_Table.id'], name='pose_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pose_pkey')
    )
    # ### end Alembic commands ###
